spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Testtest
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
      ddl-auto: update
indexing-settings:
  sites:
    - url: https://wpschool.ru
      name: Dom
    - url: http://www.playback.ru
      name: PlayBack.Ru
configparser:
  useragent: PitonSearchBot/1.0
  referrer: http://www.google.com
  timeout: 10000