spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Testtest
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
      ddl-auto: update
indexing-settings:
  sites:
    - url: https://ria.ru
      name: Ria.ru
    - url: http://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.interfax.ru
      name: Interfax.ru
    - url: https://vz.ru
      name: Vz.ru
    - url: https://www.rbc.ru
      name: Rbc.ru

configparser:
  useragent: PitonSearchBot/1.0
  referrer: http://www.google.com
  timeout: 10000