spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Testtest
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
      ddl-auto: update
indexing-settings:
  sites:
    - url: http://музей-ямщика.рф
      name: Музей Ямщика
    - url: http://playback.ru
      name: PlayBack.Ru
    - url: https://life.ru
      name: Life.ru
    - url: https://ria.ru
      name: Ria.ru
configparser:
  useragent: PitonSearchBot/1.0
  referrer: http://www.google.com
  timeout: 100000
