spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Testtest
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
      ddl-auto: update
indexing-settings:
  sites:
    - url: http://музей-ямщика.рф
      name: Музей Ямщика
    - url: http://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.rbc.ru
      name: Rbc.ru
    - url: https://ria.ru
      name: Ria.ru
configparser:
  useragent: PitonSearchBot/1.0
  referrer: http://www.google.com
  timeout: 10000