spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Testtest
    hikari:
      maximumPoolSize: 100
      connectionTimeout: 100000
      maxLifetime: 120000
      minimumIdle: 100
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
      ddl-auto: create
indexing-settings:
  sites:
    - url: http://музей-ямщика.рф
      name: Музей Ямщика
#    - url: http://playback.ru
#      name: PlayBack.Ru
    - url: https://www.lutherancathedral.ru/
      name: Lutherancathedral.ru
#    - url: https://www.svetlovka.ru/
#      name: Svetlovka.ru
configparser:
  useragent: PitonSearchBot/1.0
  referrer: http://www.google.com
  timeout: 100000
